name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build --build-arg API_PORT=${{ vars.API_PORT }} \
                       --build-arg DB_HOST=${{ vars.DB_HOST }} \
                       --build-arg DB_USERNAME=${{ secrets.DB_USERNAME }} \
                       --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
                       --build-arg DB_DATABASE=${{ vars.DB_DATABASE }} \
                       --build-arg DB_PORT=${{ vars.DB_PORT }} \
                       --build-arg AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }} \
                       --build-arg AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }} \
                       -t my-app:latest .
