name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ vars.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com

      - name: Build Docker image
        run: |
          docker build --build-arg API_PORT=${{ vars.API_PORT }} \
                       --build-arg DB_HOST=${{ vars.DB_HOST }} \
                       --build-arg DB_USERNAME=${{ secrets.DB_USERNAME }} \
                       --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
                       --build-arg DB_DATABASE=${{ vars.DB_DATABASE }} \
                       --build-arg DB_PORT=${{ vars.DB_PORT }} \
                       --build-arg AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }} \
                       --build-arg AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }} \
                       -t my-app:latest .

      - name: Tag Docker image
        run: |
          docker tag my-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/todo/todo-server:latest

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/todo/todo-server:latest

      - name: Replace variables in task definition
        run: |
          sed -i 's|${AWS_ACCOUNT_ID}|'"${{ secrets.AWS_ACCOUNT_ID }}"'|g' ecs-task-definition.json
          sed -i 's|${AWS_REGION}|'"${{ vars.AWS_REGION }}"'|g' ecs-task-definition.json
          sed -i 's|${API_PORT}|'"${{ vars.API_PORT }}"'|g' ecs-task-definition.json
          sed -i 's|${DB_HOST}|'"${{ vars.DB_HOST }}"'|g' ecs-task-definition.json
          sed -i 's|${DB_USERNAME}|'"${{ secrets.DB_USERNAME }}"'|g' ecs-task-definition.json
          sed -i 's|${DB_PASSWORD}|'"${{ secrets.DB_PASSWORD }}"'|g' ecs-task-definition.json
          sed -i 's|${DB_DATABASE}|'"${{ vars.DB_DATABASE }}"'|g' ecs-task-definition.json
          sed -i 's|${DB_PORT}|'"${{ vars.DB_PORT }}"'|g' ecs-task-definition.json
          sed -i 's|${AUTH0_AUDIENCE}|'"${{ secrets.AUTH0_AUDIENCE }}"'|g' ecs-task-definition.json
          sed -i 's|${AUTH0_DOMAIN}|'"${{ secrets.AUTH0_DOMAIN }}"'|g' ecs-task-definition.json

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ecs-task-definition.json
          service: lb-service
          cluster: kaplan-todo-server
          wait-for-service-stability: true
        env:
          AWS_REGION: eu-north-1
